surface:
  - skt
  - sp
  - ci
  - sd
  - stl1
  - stl2
  - stl3
  - stl4
  - swvl1
  - swvl2
  - swvl3
  - swvl4
plev:
  - u
  - v
  - t
  - q
catalogues:
  - era5_land
  - era5
regrid: era5
format: grib